### ISSUE TITLE
compatbility

### ISSUE THREAD

**Issue by libussa** [rundeck-plugins/vault-storage#7]
Is this compatible with rundeck 3? Do I need kv v1 in vault or is this compatible with version 2?

**Comment by ltamaster** [comment]
Hi @libussa ,

***Is this compatible with rundeck 3?***
Yes

***Do I need kv v1 in vault or is this compatible with version 2?***
You need  kv v1 in vault , it is not compatible with v2

Luis

**Comment by libussa** [comment]
Thanks for the prompt answer :)
I'm a bit confused then. I'm running a new instance of rundeck with docker-compose. Took the variable names from de docker test in this repo. The jar file for the plugin is recognized in the web UI. 
Here is my compose file:
```
version: '3'

services:
    rundeck:
        container_name: rundeck
        image: rundeck/rundeck:3.0.8
        network_mode: bridge
        volumes:
            - "./plugins/:/home/rundeck/libext/"
            - "./data/:/home/rundeck/server/data"
        environment:
              EXTERNAL_SERVER_URL: https://rundeck.domain.com
              RUNDECK_GRAILS_URL: https://rundeck.domain.com
              <LDAP config>
              RUNDECK_STORAGE_PROVIDER_1_TYPE: vault-storage
              RUNDECK_STORAGE_PROVIDER_1_PATH: keys
              RUNDECK_STORAGE_PROVIDER_1_CONFIG_SECRETBACKEND: rundeck
              RUNDECK_STORAGE_PROVIDER_1_CONFIG_PREFIX: rundeck
              RUNDECK_STORAGE_PROVIDER_1_CONFIG_ADDRESS: <url>
              RUNDECK_STORAGE_PROVIDER_1_CONFIG_TOKEN: <token>
        ports:
            - 127.0.0.1:4440:4440
```
on server start, nothing about storage happens, and keys go into the default file storage... Is there something more I need to do? I tried playing with the docker test setup but it errors out.
